export const MEDIA_CONSTANTS = {
  BADGES: {
    RESOLUTION_4K: '4k',
    RESOLUTION_HD: 'hd',
    RESOLUTION_SD: 'sd',
    IMAX: 'imax',
    DOLBY_VISION: 'dolby-vision',
    HDR10_PLUS: 'hdr10-plus',
    HDR: 'hdr',
    DOLBY_ATMOS: 'dolby-atmos',
    DOLBY_AUDIO: 'dolby-audio',
    DTS: 'dts',
    DTS_X: 'dts-x',
    AV1: 'av1',
    CC: 'cc',
    SDH: 'sdh',
    AD: 'ad',
    LOSSLESS: 'lossless',
    HI_RES_LOSSLESS: 'hi-res-lossless',
  },
  TOKENS: {
    ATMOS: 'atmos',
    DTS: 'dts',
    DOLBY: 'dolby',
    AC3: 'ac-3',
    EAC3: 'e-ac-3',
    IMAX: 'imax',
    XLL_X: 'xll x',
    XLL: 'xll',
    HDR10_PLUS: 'HDR10+',
  },
  FORMATS: {
    AAC: 'AAC',
    AVC: 'AVC',
    HEVC: 'HEVC',
    DTS: 'DTS',
    AC3: 'AC-3',
    EAC3: 'E-AC-3',
    TRUEHD: 'TrueHD',
    FLAC: 'FLAC',
    OPUS: 'Opus',
    VORBIS: 'Vorbis',
    PCM: 'PCM',
  },
} as const;
